[package]
name = "arcqml-kernel"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
num-complex.workspace = true
thiserror.workspace = true
arcqml-circuit.workspace = true
arcqml-core.workspace = true
arcqml-runtime-abi.workspace = true
arcqml-runtime-sys.workspace = true
rayon = { workspace = true, optional = true }

[features]
default = ["parallel"]
parallel = ["dep:rayon", "arcqml-core/parallel"]
